config/routes.rb
Rails.application.routes.draw do

#read all
  get 'tasks', to: 'tasks#index'

#create (one)
  get    "tasks/new",      to: "tasks#new", as:'new_task'
  post   "tasks",          to: "tasks#create"

#read one
  get 'tasks/:id', to: 'tasks#show', as:'task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#update a task
  get    "tasks/:id/edit", to: "tasks#edit" , as: "edit_task"
  patch  "tasks/:id",      to: "tasks#update"

#delete one
  delete "tasks/:id",      to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new

  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy

    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path

  end




  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
  params.require(:task).permit(:title, :details, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<!--
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
 -->

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task) %> </h2>
  <p><%= task.details %></p>
  <p>Completed: <%= task.done %></p>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>
  <p>Completed: <%= @task.done %></p>
  <%= link_to "Delete", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

  <%= link_to "back to task list", tasks_path %>

  <%= link_to 'edit this task', edit_task_path(@task) %>